// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.wmsi.sgx.model.search;

public class CriteriaBuilder extends CriteriaBuilderBase<CriteriaBuilder>{
	public static CriteriaBuilder criteria() {
		return new CriteriaBuilder();
	}

	public CriteriaBuilder(){
		super(new Criteria());
	}

	public Criteria build() {
		return getInstance();
	}
}

class CriteriaBuilderBase<GeneratorT extends CriteriaBuilderBase<GeneratorT>> {
	private Criteria instance;

	protected CriteriaBuilderBase(Criteria aInstance){
		instance = aInstance;
	}

	protected Criteria getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withField(String aValue) {
		instance.setField(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withValue(String aValue) {
		instance.setValue(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTo(Double aValue) {
		instance.setTo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFrom(Double aValue) {
		instance.setFrom(aValue);

		return (GeneratorT) this;
	}
}
