// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.wmsi.sgx.model.search;

import java.util.ArrayList;
import java.util.List;

public class SearchRequestBuilder extends SearchRequestBuilderBase<SearchRequestBuilder>{
	public static SearchRequestBuilder searchRequest() {
		return new SearchRequestBuilder();
	}

	public SearchRequestBuilder(){
		super(new SearchRequest());
	}

	public SearchRequest build() {
		return getInstance();
	}
}

class SearchRequestBuilderBase<GeneratorT extends SearchRequestBuilderBase<GeneratorT>> {
	private SearchRequest instance;

	protected SearchRequestBuilderBase(SearchRequest aInstance){
		instance = aInstance;
	}

	protected SearchRequest getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCriteria(List<Criteria> aValue) {
		instance.setCriteria(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedCriteriaElement(Criteria aValue) {
		if(instance.getCriteria() == null){
			instance.setCriteria(new ArrayList<Criteria>());
		}

		((ArrayList<Criteria>) instance.getCriteria()).add(aValue);

		return (GeneratorT) this;
	}

	public AddedCriteriaElementCriteriaBuilder withAddedCriteriaElement() {
		Criteria obj = new Criteria();

		withAddedCriteriaElement(obj);

		return new AddedCriteriaElementCriteriaBuilder(obj);
	}

	public class AddedCriteriaElementCriteriaBuilder extends CriteriaBuilderBase<AddedCriteriaElementCriteriaBuilder>{
		public AddedCriteriaElementCriteriaBuilder(Criteria aInstance){
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endCriteriaElement() {
			return (GeneratorT) SearchRequestBuilderBase.this;
		}
	}

	public static class CriteriaBuilderBase<GeneratorT extends CriteriaBuilderBase<GeneratorT>> {
		private Criteria instance;

		protected CriteriaBuilderBase(Criteria aInstance){
			instance = aInstance;
		}

		protected Criteria getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withField(String aValue) {
			instance.setField(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withValue(String aValue) {
			instance.setValue(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withTo(Double aValue) {
			instance.setTo(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withFrom(Double aValue) {
			instance.setFrom(aValue);

			return (GeneratorT) this;
		}
	}
}
