// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.wmsi.sgx.service.search;

public class DefaultAggregationBuilder extends DefaultAggregationBuilderBase<DefaultAggregationBuilder>{
	public static DefaultAggregationBuilder defaultAggregation() {
		return new DefaultAggregationBuilder();
	}

	public DefaultAggregationBuilder(){
		super(new DefaultAggregation());
	}

	public DefaultAggregation build() {
		return getInstance();
	}
}

class DefaultAggregationBuilderBase<GeneratorT extends DefaultAggregationBuilderBase<GeneratorT>> {
	private DefaultAggregation instance;

	protected DefaultAggregationBuilderBase(DefaultAggregation aInstance){
		instance = aInstance;
	}

	protected DefaultAggregation getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withValue(String aValue) {
		instance.setValue(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}
}
