//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFDataDump.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFDataDump.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ##sgxpop (
        ///	name VARCHAR(1000),
        ///	tickerSymbol VARCHAR(25),
        ///	exchangeSymbol VARCHAR(100),
        ///	isin VARCHAR(100),
        ///	short_name VARCHAR(500),
        ///	TradingItemId int,
        ///	companyId int,
        ///	currencyId smallint,
        ///	currencyISO varchar(10)
        ///);.
        /// </summary>
        internal static string createTickerTable {
            get {
                return ResourceManager.GetString("createTickerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ##sgxpop WHERE TradingItemId is null.
        /// </summary>
        internal static string exportNFCompanies {
            get {
                return ResourceManager.GetString("exportNFCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ##sgxpop WHERE TradingItemId is not null.
        /// </summary>
        internal static string exportTickerTable {
            get {
                return ResourceManager.GetString("exportTickerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct ciq.ISOCode, ciq.currencyName
        ///  FROM ciqCurrency ciq, ##sgxpop pop
        /// WHERE ciq.ISOCode = pop.currencyISO.
        /// </summary>
        internal static string exportUniqueCurrency {
            get {
                return ResourceManager.GetString("exportUniqueCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pop SET
        ///	pop.TradingItemId = ti.tradingItemId,
        ///	pop.companyId = (SELECT s.companyId FROM ciqSecurity s WHERE ti.securityId = s.securityId),
        ///	pop.currencyId = ti.currencyId,
        ///	pop.currencyISO = (SELECT c.ISOCode FROM ciqCurrency c WHERE ti.currencyId = c.currencyId)
        ///FROM
        ///	##sgxpop pop
        ///INNER JOIN
        ///    ciqTradingItem ti
        ///ON
        ///    pop.tickerSymbol = ti.tickerSymbol
        ///AND
        ///	ti.exchangeId = (SELECT ce.exchangeId FROM ciqExchange ce WHERE ce.exchangeSymbol = pop.exchangeSymbol);.
        /// </summary>
        internal static string updateTmpTickerTable {
            get {
                return ResourceManager.GetString("updateTmpTickerTable", resourceCulture);
            }
        }
    }
}
