// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.wmsi.sgx.model;

import java.util.Date;

public class CompanyBuilder extends CompanyBuilderBase<CompanyBuilder>{
	public static CompanyBuilder company() {
		return new CompanyBuilder();
	}

	public CompanyBuilder(){
		super(new Company());
	}

	public Company build() {
		return getInstance();
	}
}

class CompanyBuilderBase<GeneratorT extends CompanyBuilderBase<GeneratorT>> {
	private Company instance;

	protected CompanyBuilderBase(Company aInstance){
		instance = aInstance;
	}

	protected Company getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAvgBrokerReq(Double aValue) {
		instance.setAvgBrokerReq(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAvgVolumeM3(Double aValue) {
		instance.setAvgVolumeM3(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBeta5Yr(Double aValue) {
		instance.setBeta5Yr(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBusinessDescription(String aValue) {
		instance.setBusinessDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBvShare(Double aValue) {
		instance.setBvShare(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCapitalExpenditures(Double aValue) {
		instance.setCapitalExpenditures(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCashInvestments(Double aValue) {
		instance.setCashInvestments(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withClosePrice(Double aValue) {
		instance.setClosePrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCompanyAddress(String aValue) {
		instance.setCompanyAddress(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCompanyName(String aValue) {
		instance.setCompanyName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCompanyWebsite(String aValue) {
		instance.setCompanyWebsite(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDividendYield(Double aValue) {
		instance.setDividendYield(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEbit(Double aValue) {
		instance.setEbit(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEbitda(Double aValue) {
		instance.setEbitda(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEbitdaMargin(Double aValue) {
		instance.setEbitdaMargin(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmployees(Double aValue) {
		instance.setEmployees(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEnterpriseValue(Double aValue) {
		instance.setEnterpriseValue(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEps(Double aValue) {
		instance.setEps(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEvEbitData(Double aValue) {
		instance.setEvEbitData(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFiscalYearEnd(Date aValue) {
		instance.setFiscalYearEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFloatPercentage(Double aValue) {
		instance.setFloatPercentage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withGvKey(String aValue) {
		instance.setGvKey(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withHighPrice(Double aValue) {
		instance.setHighPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIndustry(String aValue) {
		instance.setIndustry(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIndustryGroup(String aValue) {
		instance.setIndustryGroup(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLowPrice(Double aValue) {
		instance.setLowPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMarketCap(Double aValue) {
		instance.setMarketCap(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNetIncome(Double aValue) {
		instance.setNetIncome(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNetProfitMargin(Double aValue) {
		instance.setNetProfitMargin(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withOpenPrice(Double aValue) {
		instance.setOpenPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPeRatio(Double aValue) {
		instance.setPeRatio(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPreviousCloseDate(Date aValue) {
		instance.setPreviousCloseDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPreviousClosePrice(Double aValue) {
		instance.setPreviousClosePrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPriceToBookRatio(Double aValue) {
		instance.setPriceToBookRatio(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPriceVs52WeekHigh(Double aValue) {
		instance.setPriceVs52WeekHigh(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPriceVs52WeekLow(Double aValue) {
		instance.setPriceVs52WeekLow(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSharesOutstanding(Double aValue) {
		instance.setSharesOutstanding(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSharesSoldShort(Double aValue) {
		instance.setSharesSoldShort(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTargetPrice(Double aValue) {
		instance.setTargetPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTargetPriceNum(Double aValue) {
		instance.setTargetPriceNum(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTickerCode(String aValue) {
		instance.setTickerCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalAssets(Double aValue) {
		instance.setTotalAssets(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalDebtEbitda(Double aValue) {
		instance.setTotalDebtEbitda(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalDebtEquity(Double aValue) {
		instance.setTotalDebtEquity(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalRev1YrAnnGrowth(Double aValue) {
		instance.setTotalRev1YrAnnGrowth(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalRev3YrAnnGrowth(Double aValue) {
		instance.setTotalRev3YrAnnGrowth(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalRev5YrAnnGrowth(Double aValue) {
		instance.setTotalRev5YrAnnGrowth(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTotalRevenue(Double aValue) {
		instance.setTotalRevenue(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVolume(Double aValue) {
		instance.setVolume(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withYearFounded(Integer aValue) {
		instance.setYearFounded(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withYearHigh(Double aValue) {
		instance.setYearHigh(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withYearLow(Double aValue) {
		instance.setYearLow(aValue);

		return (GeneratorT) this;
	}
}
