// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.wmsi.sgx.model.search;

public class CompanySearchRequestBuilder extends CompanySearchRequestBuilderBase<CompanySearchRequestBuilder>{
	public static CompanySearchRequestBuilder companySearchRequest() {
		return new CompanySearchRequestBuilder();
	}

	public CompanySearchRequestBuilder(){
		super(new CompanySearchRequest());
	}

	public CompanySearchRequest build() {
		return getInstance();
	}
}

class CompanySearchRequestBuilderBase<GeneratorT extends CompanySearchRequestBuilderBase<GeneratorT>> {
	private CompanySearchRequest instance;

	protected CompanySearchRequestBuilderBase(CompanySearchRequest aInstance){
		instance = aInstance;
	}

	protected CompanySearchRequest getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSearch(String aValue) {
		instance.setSearch(aValue);

		return (GeneratorT) this;
	}
}
